const QUOTES = [
    // 1–30: Original quotes
    { text: "We are what we repeatedly do. Excellence, then, is not an act, but a habit.", author: "Aristotle" },
    { text: "The secret of getting ahead is getting started.", author: "Mark Twain" },
    { text: "Discipline is choosing between what you want now and what you want most.", author: "Abraham Lincoln" },
    { text: "Small disciplines repeated with consistency every day lead to great achievements gained slowly over time.", author: "John C. Maxwell" },
    { text: "You do not rise to the level of your goals. You fall to the level of your systems.", author: "James Clear" },
    { text: "The only way to do great work is to love what you do.", author: "Steve Jobs" },
    { text: "It is not that we have a short time to live, but that we waste a good deal of it.", author: "Seneca" },
    { text: "The impediment to action advances action. What stands in the way becomes the way.", author: "Marcus Aurelius" },
    { text: "How long are you going to wait before you demand the best for yourself?", author: "Epictetus" },
    { text: "First forget inspiration. Habit is more dependable. Habit will sustain you whether you're inspired or not.", author: "Octavia Butler" },
    { text: "Motivation is what gets you started. Habit is what keeps you going.", author: "Jim Ryun" },
    { text: "Success is the sum of small efforts, repeated day in and day out.", author: "Robert Collier" },
    { text: "The chains of habit are too light to be felt until they are too heavy to be broken.", author: "Warren Buffett" },
    { text: "Be patient with yourself. Self-growth is tender; it's holy ground.", author: "Stephen Covey" },
    { text: "Every action you take is a vote for the type of person you wish to become.", author: "James Clear" },
    { text: "The best time to plant a tree was 20 years ago. The second best time is now.", author: "Chinese Proverb" },
    { text: "What you do every day matters more than what you do once in a while.", author: "Gretchen Rubin" },
    { text: "A journey of a thousand miles begins with a single step.", author: "Lao Tzu" },
    { text: "He who has a why to live can bear almost any how.", author: "Friedrich Nietzsche" },
    { text: "The mind is everything. What you think you become.", author: "Buddha" },
    { text: "Do what is right, not what is easy nor what is popular.", author: "Roy T. Bennett" },
    { text: "It does not matter how slowly you go as long as you do not stop.", author: "Confucius" },
    { text: "Knowing is not enough; we must apply. Willing is not enough; we must do.", author: "Johann Wolfgang von Goethe" },
    { text: "The water does not flow until the faucet is turned on.", author: "Louis L'Amour" },
    { text: "Your future is created by what you do today, not tomorrow.", author: "Robert Kiyosaki" },
    { text: "One day or day one. You decide.", author: "Paulo Coelho" },
    { text: "Suffer the pain of discipline or suffer the pain of regret.", author: "Jim Rohn" },
    { text: "The only person you are destined to become is the person you decide to be.", author: "Ralph Waldo Emerson" },
    { text: "Take care of your body. It's the only place you have to live.", author: "Jim Rohn" },
    { text: "Almost everything will work again if you unplug it for a few minutes — including you.", author: "Anne Lamott" },
    // 31–365: Additional quotes
    { text: "Happiness is not something ready made. It comes from your own actions.", author: "Dalai Lama" },
    { text: "The greatest wealth is health.", author: "Virgil" },
    { text: "With self-discipline most anything is possible.", author: "Theodore Roosevelt" },
    { text: "Simplicity is the ultimate sophistication.", author: "Leonardo da Vinci" },
    { text: "No man is free who is not master of himself.", author: "Epictetus" },
    { text: "Well-being is realized by small steps, but is truly no small thing.", author: "Zeno of Citium" },
    { text: "In the middle of difficulty lies opportunity.", author: "Albert Einstein" },
    { text: "The unexamined life is not worth living.", author: "Socrates" },
    { text: "Begin at once to live, and count each separate day as a separate life.", author: "Seneca" },
    { text: "Waste no more time arguing about what a good man should be. Be one.", author: "Marcus Aurelius" },
    { text: "Enjoy the little things, for one day you may look back and realize they were the big things.", author: "Robert Brault" },
    { text: "An ounce of practice is worth more than tons of preaching.", author: "Mahatma Gandhi" },
    { text: "Peace comes from within. Do not seek it without.", author: "Buddha" },
    { text: "Dwell on the beauty of life. Watch the stars, and see yourself running with them.", author: "Marcus Aurelius" },
    { text: "The body achieves what the mind believes.", author: "Napoleon Hill" },
    { text: "Do every act of your life as though it were the very last act of your life.", author: "Marcus Aurelius" },
    { text: "Health is not valued till sickness comes.", author: "Thomas Fuller" },
    { text: "You must be the change you wish to see in the world.", author: "Mahatma Gandhi" },
    { text: "What lies behind us and what lies before us are tiny matters compared to what lies within us.", author: "Ralph Waldo Emerson" },
    { text: "The soul becomes dyed with the color of its thoughts.", author: "Marcus Aurelius" },
    { text: "Fall seven times, stand up eight.", author: "Japanese Proverb" },
    { text: "Self-control is strength. Calmness is mastery.", author: "James Allen" },
    { text: "Gratitude turns what we have into enough.", author: "Aesop" },
    { text: "Rule your mind or it will rule you.", author: "Horace" },
    { text: "The mind is its own place, and in itself can make a heaven of hell, a hell of heaven.", author: "John Milton" },
    { text: "Strength does not come from physical capacity. It comes from an indomitable will.", author: "Mahatma Gandhi" },
    { text: "Where focus goes, energy flows.", author: "Tony Robbins" },
    { text: "Live as if you were to die tomorrow. Learn as if you were to live forever.", author: "Mahatma Gandhi" },
    { text: "Simplicity is the key to brilliance.", author: "Bruce Lee" },
    { text: "Our life is frittered away by detail. Simplify, simplify.", author: "Henry David Thoreau" },
    { text: "Difficulties strengthen the mind, as labor does the body.", author: "Seneca" },
    { text: "Nothing will work unless you do.", author: "Maya Angelou" },
    { text: "The privilege of a lifetime is to become who you truly are.", author: "Carl Jung" },
    { text: "He who conquers himself is the mightiest warrior.", author: "Confucius" },
    { text: "Perseverance is not a long race; it is many short races one after the other.", author: "Walter Elliot" },
    { text: "To keep the body in good health is a duty, otherwise we shall not be able to keep our mind strong.", author: "Buddha" },
    { text: "Look well into thyself; there is a source of strength which will always spring up if thou wilt always look.", author: "Marcus Aurelius" },
    { text: "The present moment is filled with joy and happiness. If you are attentive, you will see it.", author: "Thich Nhat Hanh" },
    { text: "Champions keep playing until they get it right.", author: "Billie Jean King" },
    { text: "The only discipline that lasts is self-discipline.", author: "Bum Phillips" },
    { text: "Resilience is knowing that you are the only one that has the power to pick yourself up.", author: "Mary Holloway" },
    { text: "I fear not the man who has practiced 10,000 kicks once, but the man who has practiced one kick 10,000 times.", author: "Bruce Lee" },
    { text: "Patience is also a form of action.", author: "Auguste Rodin" },
    { text: "A grateful heart is a magnet for miracles.", author: "Unknown" },
    { text: "Don't count the days. Make the days count.", author: "Muhammad Ali" },
    { text: "Luck is what happens when preparation meets opportunity.", author: "Seneca" },
    { text: "Inch by inch, life's a cinch. Yard by yard, life is hard.", author: "John Bytheway" },
    { text: "If you want to lift yourself up, lift up someone else.", author: "Booker T. Washington" },
    { text: "True life is lived when tiny changes occur.", author: "Leo Tolstoy" },
    { text: "The best revenge is massive success.", author: "Frank Sinatra" },
    { text: "I am not a product of my circumstances. I am a product of my decisions.", author: "Stephen Covey" },
    { text: "Energy and persistence conquer all things.", author: "Benjamin Franklin" },
    { text: "The more you sweat in training, the less you bleed in combat.", author: "Richard Marcinko" },
    { text: "Be where you are, not where you think you should be.", author: "Unknown" },
    { text: "Arise, awake, and stop not until the goal is reached.", author: "Swami Vivekananda" },
    { text: "To enjoy good health, to bring true happiness, one must first discipline the mind.", author: "Buddha" },
    { text: "What we achieve inwardly will change outer reality.", author: "Plutarch" },
    { text: "Our greatest glory is not in never falling, but in rising every time we fall.", author: "Confucius" },
    { text: "Happiness depends upon ourselves.", author: "Aristotle" },
    { text: "The obstacle is the path.", author: "Zen Proverb" },
    { text: "Out of suffering have emerged the strongest souls.", author: "Khalil Gibran" },
    { text: "A calm mind brings inner strength and self-confidence.", author: "Dalai Lama" },
    { text: "Long-term consistency trumps short-term intensity.", author: "Bruce Lee" },
    { text: "The only limit to our realization of tomorrow will be our doubts of today.", author: "Franklin D. Roosevelt" },
    { text: "Excellence is not a singular act, but a habit. You are what you repeatedly do.", author: "Shaquille O'Neal" },
    { text: "If you are at peace you are living in the present.", author: "Lao Tzu" },
    { text: "Habits are the compound interest of self-improvement.", author: "James Clear" },
    { text: "Our bodies are our gardens — our wills are our gardeners.", author: "William Shakespeare" },
    { text: "Make each day your masterpiece.", author: "John Wooden" },
    { text: "Sow a thought, reap an action; sow an action, reap a habit; sow a habit, reap a character.", author: "Stephen Covey" },
    { text: "It is during our darkest moments that we must focus to see the light.", author: "Aristotle" },
    { text: "That which does not kill us makes us stronger.", author: "Friedrich Nietzsche" },
    { text: "He is wise who rejoices for what he has, not grieves for what he has not.", author: "Epictetus" },
    { text: "The successful warrior is the average man, with laser-like focus.", author: "Bruce Lee" },
    { text: "Mind is a flexible mirror, adjust it to see a better world.", author: "Amit Ray" },
    { text: "You can start where you are and change the ending.", author: "C.S. Lewis" },
    { text: "The man who moves a mountain begins by carrying away small stones.", author: "Confucius" },
    { text: "Be yourself; everyone else is already taken.", author: "Oscar Wilde" },
    { text: "Tension is who you think you should be. Relaxation is who you are.", author: "Chinese Proverb" },
    { text: "When you arise in the morning, think of what a precious privilege it is to be alive.", author: "Marcus Aurelius" },
    { text: "Progress is not achieved by luck or accident, but by working on yourself daily.", author: "Epictetus" },
    { text: "There is no path to happiness. Happiness is the path.", author: "Buddha" },
    { text: "The measure of who we are is what we do with what we have.", author: "Vince Lombardi" },
    { text: "Great things are done by a series of small things brought together.", author: "Vincent van Gogh" },
    { text: "Let food be thy medicine and medicine be thy food.", author: "Hippocrates" },
    { text: "Very little is needed to make a happy life; it is all within yourself, in your way of thinking.", author: "Marcus Aurelius" },
    { text: "To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.", author: "Ralph Waldo Emerson" },
    { text: "Courage is not having the strength to go on; it is going on when you don't have the strength.", author: "Theodore Roosevelt" },
    { text: "The secret of change is to focus all energy not on fighting the old, but on building the new.", author: "Socrates" },
    { text: "We suffer more often in imagination than in reality.", author: "Seneca" },
    { text: "It always seems impossible until it's done.", author: "Nelson Mandela" },
    { text: "You have power over your mind — not outside events. Realize this, and you will find strength.", author: "Marcus Aurelius" },
    { text: "Hard times don't create heroes; it is during hard times when the hero within us is revealed.", author: "Bob Riley" },
    { text: "Gratitude is the healthiest of all human emotions.", author: "Zig Ziglar" },
    { text: "The greatest remedy for anger is delay.", author: "Seneca" },
    { text: "Mastering others is strength. Mastering yourself is true power.", author: "Lao Tzu" },
    { text: "It's not whether you get knocked down; it's whether you get up.", author: "Vince Lombardi" },
    { text: "A man is but the product of his thoughts. What he thinks, he becomes.", author: "Mahatma Gandhi" },
    { text: "Don't let yesterday take up too much of today.", author: "Will Rogers" },
    { text: "He who is not a good servant will not be a good master.", author: "Plato" },
    { text: "Perfection is not attainable, but if we chase perfection we can catch excellence.", author: "Vince Lombardi" },
    { text: "You will never always be motivated. You have to learn to be disciplined.", author: "Unknown" },
    { text: "What we fear doing most is usually what we most need to do.", author: "Tim Ferriss" },
    { text: "The best fighter is never angry.", author: "Lao Tzu" },
    { text: "Gratitude makes sense of our past, brings peace for today, and creates a vision for tomorrow.", author: "Melody Beattie" },
    { text: "The only impossible journey is the one you never begin.", author: "Tony Robbins" },
    { text: "Do not dwell in the past, do not dream of the future, concentrate the mind on the present moment.", author: "Buddha" },
    { text: "Once you replace negative thoughts with positive ones, you'll start having positive results.", author: "Willie Nelson" },
    { text: "Continuous improvement is better than delayed perfection.", author: "Mark Twain" },
    { text: "There is only one way to happiness, and that is to cease worrying about things beyond our power.", author: "Epictetus" },
    { text: "Motivation doesn't last. Well, neither does bathing — that's why we recommend it daily.", author: "Zig Ziglar" },
    { text: "The pain you feel today will be the strength you feel tomorrow.", author: "Arnold Schwarzenegger" },
    { text: "Genius is one percent inspiration and ninety-nine percent perspiration.", author: "Thomas Edison" },
    { text: "Your body hears everything your mind says.", author: "Naomi Judd" },
    { text: "Do not go where the path may lead, go instead where there is no path and leave a trail.", author: "Ralph Waldo Emerson" },
    { text: "Wealth consists not in having great possessions, but in having few wants.", author: "Epictetus" },
    { text: "If you want to be happy, be.", author: "Leo Tolstoy" },
    { text: "Silence is a source of great strength.", author: "Lao Tzu" },
    { text: "Act without expectation.", author: "Lao Tzu" },
    { text: "When the breath is calmed the mind too will be still.", author: "Hatha Yoga Pradipika" },
    { text: "A person can change their future by merely changing their attitude.", author: "Oprah Winfrey" },
    { text: "Health is a state of complete harmony of the body, mind, and spirit.", author: "B.K.S. Iyengar" },
    { text: "Success is walking from failure to failure with no loss of enthusiasm.", author: "Winston Churchill" },
    { text: "The difference between who you are and who you want to be is what you do.", author: "Unknown" },
    { text: "Strive not to be a success, but rather to be of value.", author: "Albert Einstein" },
    { text: "You are never too old to set another goal or to dream a new dream.", author: "C.S. Lewis" },
    { text: "All that we are is the result of what we have thought.", author: "Buddha" },
    { text: "Start where you are. Use what you have. Do what you can.", author: "Arthur Ashe" },
    { text: "Doubt is the origin of wisdom.", author: "Rene Descartes" },
    { text: "Action is the foundational key to all success.", author: "Pablo Picasso" },
    { text: "Nothing is impossible, the word itself says I'm possible!", author: "Audrey Hepburn" },
    { text: "Change your thoughts and you change your world.", author: "Norman Vincent Peale" },
    { text: "The more man meditates upon good thoughts, the better will be his world.", author: "Confucius" },
    { text: "Not how long, but how well you have lived is the main thing.", author: "Seneca" },
    { text: "Keep your face always toward the sunshine — and shadows will fall behind you.", author: "Walt Whitman" },
    { text: "Don't wish it were easier. Wish you were better.", author: "Jim Rohn" },
    { text: "To think is easy. To act is hard. The hardest thing is to act in accordance with your thinking.", author: "Johann Wolfgang von Goethe" },
    { text: "The best preparation for tomorrow is doing your best today.", author: "H. Jackson Brown Jr." },
    { text: "If something is important enough, even if the odds are against you, you should still do it.", author: "Elon Musk" },
    { text: "Be kind whenever possible. It is always possible.", author: "Dalai Lama" },
    { text: "The wise man does at once what the fool does finally.", author: "Niccolo Machiavelli" },
    { text: "When we are no longer able to change a situation, we are challenged to change ourselves.", author: "Viktor Frankl" },
    { text: "A healthy outside starts from the inside.", author: "Robert Urich" },
    { text: "Between stimulus and response there is a space. In that space is our power to choose our response.", author: "Viktor Frankl" },
    { text: "I hated every minute of training, but I said, don't quit. Suffer now and live as a champion.", author: "Muhammad Ali" },
    { text: "You don't have to be great to start, but you have to start to be great.", author: "Zig Ziglar" },
    { text: "Discipline is the bridge between goals and accomplishment.", author: "Jim Rohn" },
    { text: "Life isn't about finding yourself. Life is about creating yourself.", author: "George Bernard Shaw" },
    { text: "He who has health has hope, and he who has hope has everything.", author: "Thomas Carlyle" },
    { text: "The only real mistake is the one from which we learn nothing.", author: "Henry Ford" },
    { text: "What is not started today is never finished tomorrow.", author: "Johann Wolfgang von Goethe" },
    { text: "The happiness of your life depends upon the quality of your thoughts.", author: "Marcus Aurelius" },
    { text: "Hardships often prepare ordinary people for an extraordinary destiny.", author: "C.S. Lewis" },
    { text: "We cannot solve our problems with the same thinking we used when we created them.", author: "Albert Einstein" },
    { text: "Be the change that you wish to see in the world.", author: "Mahatma Gandhi" },
    { text: "The power of imagination makes us infinite.", author: "John Muir" },
    { text: "If you want something you've never had, you must be willing to do something you've never done.", author: "Thomas Jefferson" },
    { text: "Each morning we are born again. What we do today is what matters most.", author: "Buddha" },
    { text: "A person who never made a mistake never tried anything new.", author: "Albert Einstein" },
    { text: "It is health that is the real wealth, and not pieces of gold and silver.", author: "Mahatma Gandhi" },
    { text: "Believe you can and you're halfway there.", author: "Theodore Roosevelt" },
    { text: "He who angers you conquers you.", author: "Elizabeth Kenny" },
    { text: "Life is 10% what happens to you and 90% how you react to it.", author: "Charles R. Swindoll" },
    { text: "The mind that is anxious about future events is miserable.", author: "Seneca" },
    { text: "If you don't like something, change it. If you can't change it, change your attitude.", author: "Maya Angelou" },
    { text: "Endurance is one of the most difficult disciplines, but it is to the one who endures that the final victory comes.", author: "Buddha" },
    { text: "No one saves us but ourselves. No one can and no one may. We ourselves must walk the path.", author: "Buddha" },
    { text: "Turn your wounds into wisdom.", author: "Oprah Winfrey" },
    { text: "Stay hungry, stay foolish.", author: "Steve Jobs" },
    { text: "Absorb what is useful, discard what is not, add what is uniquely your own.", author: "Bruce Lee" },
    { text: "If there is no struggle, there is no progress.", author: "Frederick Douglass" },
    { text: "The secret of health for both mind and body is not to mourn for the past, nor to worry about the future.", author: "Buddha" },
    { text: "What counts is not the number of hours you put in, but how much you put in the hours.", author: "Unknown" },
    { text: "Feeling gratitude and not expressing it is like wrapping a present and not giving it.", author: "William Arthur Ward" },
    { text: "You are confined only by the walls you build yourself.", author: "Andrew Murphy" },
    { text: "He who is contented is rich.", author: "Lao Tzu" },
    { text: "Tough times never last, but tough people do.", author: "Robert H. Schuller" },
    { text: "The first step toward change is awareness. The second step is acceptance.", author: "Nathaniel Branden" },
    { text: "Success isn't always about greatness. It's about consistency.", author: "Dwayne Johnson" },
    { text: "It is not the strongest of the species that survives, but the one most adaptable to change.", author: "Charles Darwin" },
    { text: "Look deep into nature, and then you will understand everything better.", author: "Albert Einstein" },
    { text: "Don't judge each day by the harvest you reap but by the seeds that you plant.", author: "Robert Louis Stevenson" },
    { text: "Either you run the day, or the day runs you.", author: "Jim Rohn" },
    { text: "The greatest glory in living lies not in never falling, but in rising every time we fall.", author: "Nelson Mandela" },
    { text: "Take the first step in faith. You don't have to see the whole staircase, just take the first step.", author: "Martin Luther King Jr." },
    { text: "Knowing yourself is the beginning of all wisdom.", author: "Aristotle" },
    { text: "Peace is the result of retraining your mind to process life as it is.", author: "Wayne Dyer" },
    { text: "If you can dream it, you can do it.", author: "Walt Disney" },
    { text: "The way to get started is to quit talking and begin doing.", author: "Walt Disney" },
    { text: "The world breaks everyone, and afterward, some are strong at the broken places.", author: "Ernest Hemingway" },
    { text: "Concentration is the secret of strength.", author: "Ralph Waldo Emerson" },
    { text: "An early-morning walk is a blessing for the whole day.", author: "Henry David Thoreau" },
    { text: "I will prepare and some day my chance will come.", author: "Abraham Lincoln" },
    { text: "The purpose of our lives is to be happy.", author: "Dalai Lama" },
    { text: "You miss 100% of the shots you don't take.", author: "Wayne Gretzky" },
    { text: "The only person you should try to be better than is the person you were yesterday.", author: "Unknown" },
    { text: "Do the difficult things while they are easy and do the great things while they are small.", author: "Lao Tzu" },
    { text: "What you get by achieving your goals is not as important as what you become by achieving them.", author: "Zig Ziglar" },
    { text: "Self-discipline begins with the mastery of your thoughts.", author: "Napoleon Hill" },
    { text: "I've failed over and over and over again in my life. And that is why I succeed.", author: "Michael Jordan" },
    { text: "Health is the greatest gift, contentment the greatest wealth, faithfulness the best relationship.", author: "Buddha" },
    { text: "When you change the way you look at things, the things you look at change.", author: "Wayne Dyer" },
    { text: "Things do not change; we change.", author: "Henry David Thoreau" },
    { text: "Every morning brings new potential, but if you dwell on yesterday, you tend to overlook tremendous opportunities.", author: "Harvey Mackay" },
    { text: "Simplicity is making the journey of this life with just baggage enough.", author: "Charles Dudley Warner" },
    { text: "Dream big and dare to fail.", author: "Norman Vaughan" },
    { text: "A river cuts through rock not because of its power, but because of its persistence.", author: "Jim Watkins" },
    { text: "Our greatest weakness lies in giving up. The most certain way to succeed is to try just one more time.", author: "Thomas Edison" },
    { text: "You cannot swim for new horizons until you have courage to lose sight of the shore.", author: "William Faulkner" },
    { text: "The best time to plant a tree is now.", author: "African Proverb" },
    { text: "Persistence guarantees that results are inevitable.", author: "Paramahansa Yogananda" },
    { text: "The mind is not a vessel to be filled, but a fire to be kindled.", author: "Plutarch" },
    { text: "To be calm is the highest achievement of the self.", author: "Zen Proverb" },
    { text: "What we do today determines who we will be tomorrow.", author: "Tim Fargo" },
    { text: "Quality is not an act. It is a habit.", author: "Aristotle" },
    { text: "Simplicity is the nature of great souls.", author: "Papa Ramadas" },
    { text: "You must do the thing you think you cannot do.", author: "Eleanor Roosevelt" },
    { text: "Rest when you're weary. Refresh and renew yourself, your body, your mind, your spirit. Then get back to work.", author: "Ralph Marston" },
    { text: "The world is full of magical things patiently waiting for our wits to grow sharper.", author: "Bertrand Russell" },
    { text: "If you always do what you've always done, you'll always get what you've always got.", author: "Henry Ford" },
    { text: "Courage is resistance to fear, mastery of fear — not absence of fear.", author: "Mark Twain" },
    { text: "By failing to prepare, you are preparing to fail.", author: "Benjamin Franklin" },
    { text: "Let us always meet each other with smile, for the smile is the beginning of love.", author: "Mother Teresa" },
    { text: "One small positive thought in the morning can change your whole day.", author: "Dalai Lama" },
    { text: "To be without some of the things you want is an indispensable part of happiness.", author: "Bertrand Russell" },
    { text: "The measure of intelligence is the ability to change.", author: "Albert Einstein" },
    { text: "Hard work beats talent when talent doesn't work hard.", author: "Tim Notke" },
    { text: "No pressure, no diamonds.", author: "Thomas Carlyle" },
    { text: "Wherever you are, be there totally.", author: "Eckhart Tolle" },
    { text: "The wise rest at least as hard as they work.", author: "Arianna Huffington" },
    { text: "Give yourself permission to slow down.", author: "Brene Brown" },
    { text: "The rhythm of the body, the melody of the mind, and the harmony of the soul create the symphony of life.", author: "B.K.S. Iyengar" },
    { text: "Set peace of mind as your highest goal, and organize your life around it.", author: "Brian Tracy" },
    { text: "Life shrinks or expands in proportion to one's courage.", author: "Anais Nin" },
    { text: "Who looks outside, dreams; who looks inside, awakes.", author: "Carl Jung" },
    { text: "Happiness is when what you think, what you say, and what you do are in harmony.", author: "Mahatma Gandhi" },
    { text: "Success usually comes to those who are too busy to be looking for it.", author: "Henry David Thoreau" },
    { text: "In a gentle way, you can shake the world.", author: "Mahatma Gandhi" },
    { text: "A mind that is stretched by a new experience can never go back to its old dimensions.", author: "Oliver Wendell Holmes" },
    { text: "Choose to be optimistic; it feels better.", author: "Dalai Lama" },
    { text: "Dripping water hollows out stone, not through force but through persistence.", author: "Ovid" },
    { text: "The greatest weapon against stress is our ability to choose one thought over another.", author: "William James" },
    { text: "We are all in the gutter, but some of us are looking at the stars.", author: "Oscar Wilde" },
    { text: "Do what you can, with what you have, where you are.", author: "Theodore Roosevelt" },
    { text: "Adopt the pace of nature: her secret is patience.", author: "Ralph Waldo Emerson" },
    { text: "Ability is what you're capable of. Motivation determines what you do. Attitude determines how well you do it.", author: "Lou Holtz" },
    { text: "The struggle you're in today is developing the strength you need for tomorrow.", author: "Robert Tew" },
    { text: "Breathe. Let go. And remind yourself that this very moment is the only one you know you have for sure.", author: "Oprah Winfrey" },
    { text: "Gratitude is the fairest blossom which springs from the soul.", author: "Henry Ward Beecher" },
    { text: "The art of being wise is the art of knowing what to overlook.", author: "William James" },
    { text: "Respect your body. It's the only one you get.", author: "Unknown" },
    { text: "Holding on to anger is like grasping a hot coal — you are the one who gets burned.", author: "Buddha" },
    { text: "Winning means you're willing to go longer, work harder, and give more than anyone else.", author: "Vince Lombardi" },
    { text: "The first wealth is health.", author: "Ralph Waldo Emerson" },
    { text: "Habit is a cable; we weave a thread of it each day, and at last we cannot break it.", author: "Horace Mann" },
    { text: "Progress, not perfection, is what we should be asking of ourselves.", author: "Julia Cameron" },
    { text: "Almost everything worthwhile carries with it some sort of risk.", author: "John F. Kennedy" },
    { text: "A champion is defined not by their wins but by how they can recover when they fall.", author: "Serena Williams" },
    { text: "Sleep is the best meditation.", author: "Dalai Lama" },
    { text: "Never confuse a single defeat with a final defeat.", author: "F. Scott Fitzgerald" },
    { text: "It is never too late to be what you might have been.", author: "George Eliot" },
    { text: "Small daily improvements over time lead to stunning results.", author: "Robin Sharma" },
    { text: "You are one workout away from a good mood.", author: "Unknown" },
    { text: "The more grateful I am, the more beauty I see.", author: "Mary Davis" },
    { text: "Don't let what you cannot do interfere with what you can do.", author: "John Wooden" },
    { text: "With the new day comes new strength and new thoughts.", author: "Eleanor Roosevelt" },
    { text: "Without health, life is not life; it is only a state of languor and suffering.", author: "Rabelais" },
    { text: "Be happy for this moment. This moment is your life.", author: "Omar Khayyam" },
    { text: "He who is brave is free.", author: "Seneca" },
    { text: "Yesterday is gone. Tomorrow has not yet come. We have only today. Let us begin.", author: "Mother Teresa" },
    { text: "In the depth of winter, I finally learned that within me there lay an invincible summer.", author: "Albert Camus" },
    { text: "Life begins at the end of your comfort zone.", author: "Neale Donald Walsch" },
    { text: "Your calm mind is the ultimate weapon against your challenges.", author: "Bryant McGill" },
    { text: "Everything you've ever wanted is on the other side of fear.", author: "George Addair" },
    { text: "Don't let the noise of others' opinions drown out your own inner voice.", author: "Steve Jobs" },
    { text: "Today is a new day. Don't let your history interfere with your destiny.", author: "Steve Maraboli" },
    { text: "Happiness is the highest form of health.", author: "Dalai Lama" },
    { text: "I attribute my success to this: I never gave or took any excuse.", author: "Florence Nightingale" },
    { text: "The only way to make sense out of change is to plunge into it, move with it, and join the dance.", author: "Alan Watts" },
    { text: "If you get tired, learn to rest, not to quit.", author: "Banksy" },
    { text: "Great acts are made up of small deeds.", author: "Lao Tzu" },
    { text: "The soul always knows what to do to heal itself. The challenge is to silence the mind.", author: "Caroline Myss" },
    { text: "Simplicity is the keynote of all true elegance.", author: "Coco Chanel" },
    { text: "A grateful mind is a great mind which eventually attracts to itself great things.", author: "Plato" },
    { text: "Strength grows in the moments when you think you can't go on but you keep going anyway.", author: "Unknown" },
    { text: "Sometimes the most productive thing you can do is relax.", author: "Mark Black" },
    { text: "Physical fitness is the first requisite of happiness.", author: "Joseph Pilates" },
    { text: "We must let go of the life we have planned, so as to accept the one that is waiting for us.", author: "Joseph Campbell" },
    { text: "Happiness resides not in possessions, and not in gold; happiness dwells in the soul.", author: "Democritus" },
    { text: "Your body is a temple, but only if you treat it as one.", author: "Astrid Alauda" },
    { text: "The key is not to prioritize what's on your schedule, but to schedule your priorities.", author: "Stephen Covey" },
    { text: "Don't be pushed around by the fears in your mind. Be led by the dreams in your heart.", author: "Roy T. Bennett" },
    { text: "The only journey is the one within.", author: "Rainer Maria Rilke" },
    { text: "Time and health are two precious assets that we don't recognize until they have been depleted.", author: "Denis Waitley" },
    { text: "Our patience will achieve more than our force.", author: "Edmund Burke" },
    { text: "If you surrender to the wind, you can ride it.", author: "Toni Morrison" },
    { text: "Motivation gets you going, but discipline keeps you growing.", author: "John C. Maxwell" },
    { text: "Difficulties are things that show a person what they are.", author: "Epictetus" },
    { text: "Let go of what you can't control. Focus on what you can.", author: "Unknown" },
    { text: "He who fears he shall suffer, already suffers what he fears.", author: "Michel de Montaigne" },
    { text: "What matters most is how well you walk through the fire.", author: "Charles Bukowski" },
    { text: "The wound is the place where the Light enters you.", author: "Rumi" },
    { text: "There is more to life than increasing its speed.", author: "Mahatma Gandhi" },
    { text: "Finish each day and be done with it. You have done what you could.", author: "Ralph Waldo Emerson" },
    { text: "Stillness is where creativity and solutions are found.", author: "Eckhart Tolle" },
    { text: "True silence is the rest of the mind, and is to the spirit what sleep is to the body.", author: "William Penn" },
    { text: "The best way out is always through.", author: "Robert Frost" },
    { text: "You have within you right now, everything you need to deal with whatever the world can throw at you.", author: "Brian Tracy" },
    { text: "Man does not simply exist but always decides what his existence will be.", author: "Viktor Frankl" },
    { text: "The only thing standing between you and your goal is the story you keep telling yourself.", author: "Jordan Belfort" },
    { text: "In three words I can sum up everything I've learned about life: it goes on.", author: "Robert Frost" },
    { text: "Gratitude is not only the greatest of virtues but the parent of all others.", author: "Cicero" },
    { text: "Simplicity is an exact medium between too little and too much.", author: "Joshua Reynolds" },
    { text: "The harder the conflict, the greater the triumph.", author: "George Washington" },
    { text: "Don't wait for the perfect moment. Take the moment and make it perfect.", author: "Zoey Sayward" },
    { text: "Nothing can harm you as much as your own thoughts unguarded.", author: "Buddha" },
    { text: "Take rest; a field that has rested gives a bountiful crop.", author: "Ovid" },
    { text: "A disciplined mind leads to happiness, and an undisciplined mind leads to suffering.", author: "Dalai Lama" },
    { text: "You can't stop the waves, but you can learn to surf.", author: "Jon Kabat-Zinn" },
    { text: "The only real failure in life is not to be true to the best one knows.", author: "Buddha" },
    { text: "Have patience. All things are difficult before they become easy.", author: "Saadi" },
    { text: "Every champion was once a contender that refused to give up.", author: "Rocky Balboa" },
    { text: "Strength doesn't come from what you can do. It comes from overcoming the things you once thought you couldn't.", author: "Rikki Rogers" },
    { text: "What does not destroy me, makes me stronger.", author: "Friedrich Nietzsche" },
    { text: "The world is changed by your example, not by your opinion.", author: "Paulo Coelho" },
    { text: "Mindfulness is a way of befriending ourselves and our experience.", author: "Jon Kabat-Zinn" },
    { text: "If you always put limits on everything you do, it will spread into your work and into your life.", author: "Bruce Lee" },
    { text: "Until you make the unconscious conscious, it will direct your life and you will call it fate.", author: "Carl Jung" },
    { text: "The only true wisdom is in knowing you know nothing.", author: "Socrates" },
    { text: "The way I see it, if you want the rainbow, you gotta put up with the rain.", author: "Dolly Parton" },
    { text: "Do not anticipate trouble, or worry about what may never happen. Keep in the sunlight.", author: "Benjamin Franklin" },
    { text: "The root of suffering is attachment.", author: "Buddha" },
    { text: "Walking is man's best medicine.", author: "Hippocrates" },
    { text: "Everything in moderation, including moderation.", author: "Oscar Wilde" },
    { text: "The greatest of all mistakes is to do nothing because you can only do a little.", author: "Sydney Smith" },
];
